name: Contribution Snake SVG
on:
  # 每日自动更新
  schedule:
    - cron: "0 0 * * *"
  # 手动运行
  workflow_dispatch:
  # 提交代码时刷新
  push:
    branches: [ main ]

# 关键权限，不写会推送失败
permissions:
  contents: write

jobs:
  generate-snake:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repo
        uses: actions/checkout@v4

      # 轻量svg-only版本
      - name: Build snake svg
        uses: Platane/snk/svg-only@v3
        with:
          github_user_name: ${{ github.repository_owner }}
          outputs: |
            dist/github-snake.svg
            dist/github-snake-dark.svg?palette=github-dark
            dist/blue-snake.svg?color_snake=#1677ff&color_dots=#f0f7ff,#bfdbfe,#93c5fd,#3b82f6,#1d4ed8

          color_snake: "#FF0000"   
      # 把生成的svg推到output分支
      - name: Publish svg to output branch
        uses: peaceiris/actions-gh-pages@v4
        with:
          github_token: ${{ secrets.GITHUB_TOKEN }}
          publish_dir: ./dist
          publish_branch: output
          force_orphan: true
          commit_message: Auto update snake svg [skip ci]
